name: dbt_service
version: '1.0.0'

profile: dbt_service

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Keep seed/reference data in raw landing zone (e.g., quarantine lists, product catalog)
  dbt_service:
    +schema: raw
    product_catalog:
      +column_types:
        price: FLOAT64
        cost: FLOAT64
        stock_quantity: INT64
        last_updated: TIMESTAMP
      +quote_columns: false

models:
  dbt_service:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

snapshots:
  # Store historical SCD Type 2 state in dedicated dataset
  dbt_service:
    +schema: snapshots
